# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# files: ^(backend|frontend)/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
        # exclude: |
        #     (?x)^(
        #         backend/app/email-templates/build/.*
        #     )$
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2 # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        args:
          - "--config=./backend/pyproject.toml"
        additional_dependencies:
          - "sqlalchemy2-stubs"
          - "pydantic"
          - "pytest"
          - "fastapi"
          - "langchain_google_genai"
          - "python-dotenv"
